---
title: "Lists - In Class Exercises"
author: "Dr. Shoemaker"
date: "DATA 2401"
output: html_document
---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
playing_card = list(
  suit = "Diamonds",
  face = "King",
  value = 13
)

```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
deck = list(
  suits = c("Heart","Diamond","Spade","Clubs"),
  faces = c("Ace","Jack","Queen","King"),
  values = c(Ace = 1, Jack = 11, Queen = 12, King = 13)
)

```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")
Newlist[[1]]+1

```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will give all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")
numbers = b$a[-2]
number_1 = b$a > 7
b$a[number_1]

```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA") 
x$z = "NewItem"
x
```
